# Install Snow PC Agent auto-start (no Admin required by default).
#
#   cd ...\pc-agent
#   .\install-autostart.ps1 -Token "same-as-acer"
#
# Methods (tried in order):
#   1) Scheduled Task, current user, RunLevel Limited  (no admin)
#   2) Startup folder shortcut                          (always works)
#
# Avoids RunLevel Highest (needs Admin -> "Erisim engellendi").

param(
  [string]$Token = "",
  [string]$TaskName = "SnowPcAgent"
)

$ErrorActionPreference = "Stop"
$AgentDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location -Path $AgentDir

function Write-Step([string]$msg) { Write-Host "[*] $msg" }
function Write-Ok([string]$msg) { Write-Host "[OK] $msg" }
function Write-Warn([string]$msg) { Write-Host "[!] $msg" }

# --- 1) .env ---
$EnvFile = Join-Path $AgentDir ".env"
if ($Token) {
  @(
    "SNOW_PC_AGENT_TOKEN=$Token"
    "SNOW_PC_AGENT_PORT=8790"
    "SNOW_PC_AGENT_HOST=0.0.0.0"
  ) | Set-Content -Path $EnvFile -Encoding UTF8
  Write-Ok "Wrote $EnvFile"
}
elseif (-not (Test-Path -Path $EnvFile)) {
  $example = Join-Path $AgentDir ".env.example"
  if (Test-Path -Path $example) {
    Copy-Item -Path $example -Destination $EnvFile
  }
  Write-Warn "Edit .env and set SNOW_PC_AGENT_TOKEN (same as Acer), then re-run if needed."
}

# --- 2) venv + deps ---
$venvPy = Join-Path $AgentDir ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $venvPy)) {
  Write-Step "Creating .venv ..."
  python -m venv (Join-Path $AgentDir ".venv")
}
if (-not (Test-Path -Path $venvPy)) {
  throw "python venv failed. Is Python installed and on PATH?"
}
Write-Step "Installing requirements ..."
& $venvPy -m pip install -q --upgrade pip
& $venvPy -m pip install -q -r (Join-Path $AgentDir "requirements.txt")

$vbs = Join-Path $AgentDir "start-hidden.vbs"
if (-not (Test-Path -Path $vbs)) {
  throw "start-hidden.vbs missing in $AgentDir"
}

$taskOk = $false

# --- 3a) Scheduled Task (current user, LIMITED - no admin) ---
Write-Step "Registering Scheduled Task (current user, no admin) ..."
try {
  $old = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  if ($null -ne $old) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
  }

  $action = New-ScheduledTaskAction `
    -Execute "wscript.exe" `
    -Argument "`"$vbs`"" `
    -WorkingDirectory $AgentDir

  $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -MultipleInstances IgnoreNew

  # Limited = no UAC elevation required to register
  $principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Limited

  $null = Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Force `
    -Description "Snow PC Agent :8790 auto-start at logon"

  $check = Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop
  if ($null -eq $check) { throw "Task not found after register" }
  $taskOk = $true
  Write-Ok "Scheduled Task '$TaskName' registered"
}
catch {
  Write-Warn "Scheduled Task failed: $($_.Exception.Message)"
  Write-Warn "Falling back to Startup folder (works without admin)."
}

# --- 3b) Startup folder (always, as reliable backup) ---
$startupDir = [Environment]::GetFolderPath("Startup")
$startupVbs = Join-Path $startupDir "SnowPcAgent.vbs"
$startupContent = @"
' Auto-generated by install-autostart.ps1 - starts Snow PC Agent hidden
Set sh = CreateObject("WScript.Shell")
sh.Run "wscript.exe ""$vbs""", 0, False
"@
Set-Content -Path $startupVbs -Value $startupContent -Encoding ASCII
Write-Ok "Startup shortcut: $startupVbs"

# --- 4) Start now ---
Write-Step "Starting agent now ..."
if ($taskOk) {
  try {
    Start-ScheduledTask -TaskName $TaskName -ErrorAction Stop
  }
  catch {
    Write-Warn "Start-ScheduledTask failed, launching VBS directly: $($_.Exception.Message)"
    Start-Process -FilePath "wscript.exe" -ArgumentList "`"$vbs`"" -WorkingDirectory $AgentDir
  }
}
else {
  Start-Process -FilePath "wscript.exe" -ArgumentList "`"$vbs`"" -WorkingDirectory $AgentDir
}

Start-Sleep -Seconds 4

$healthy = $false
try {
  $r = Invoke-RestMethod -Uri "http://127.0.0.1:8790/health" -TimeoutSec 6
  $json = $r | ConvertTo-Json -Compress
  Write-Ok "Health: $json"
  $healthy = $true
}
catch {
  Write-Warn "Health not ready yet. Check:"
  Write-Host "  - $(Join-Path $AgentDir 'logs')"
  Write-Host "  - .env has SNOW_PC_AGENT_TOKEN"
  Write-Host "  - Wait a few seconds and open http://127.0.0.1:8790/health"
}

Write-Host ""
Write-Host "==== Summary ===="
Write-Host "  Scheduled Task : $(if ($taskOk) { 'YES' } else { 'NO (using Startup folder)' })"
Write-Host "  Startup folder : YES ($startupVbs)"
Write-Host "  Health now     : $(if ($healthy) { 'YES' } else { 'pending' })"
Write-Host "  Logs           : $(Join-Path $AgentDir 'logs')"
Write-Host ""
Write-Host "After reboot / logon, agent starts by itself."
Write-Host "Remove: .\uninstall-autostart.ps1"
